# Generated by Django 3.1 on 2021-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('foodtype', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=50)),
            ],
        ),
    ]
